[phases.setup]
aptPkgs = ["libcairo2-dev", "libpango1.0-dev", "libjpeg-dev", "libgif-dev", "librsvg2-dev", "libpixman-1-dev", "pkg-config", "python3", "make", "g++"]

[phases.install]
cmds = ["npm ci --include=dev"]

[start]
cmd = "npm start"
